language: python
python:
  - "3.9"
install:
  - pip install -e .
  - pip install pytest-cov codecov
script:
  - pytest --cov==src tests
after_success:
  - bash <(curl -s https://codecov.io/bash) -t cb2883eb-1d16-4326-8cd5-79187c439692